# Force load Xresources config
xrdb ~/.Xresources

# Set keyboard region
setxkbmap -layout gb

# Set desktop color
xsetroot -solid "#4CAF50"

# Start VBox client integrations
#exec /usr/bin/VBoxClient-all

# Start i3
exec i3
